import Head from 'next/head'
import { useRouter } from 'next/router';
import { useEffect } from 'react';



export default function Home() {

  const router = useRouter()

  useEffect(() => {
    router.push("/tasks")
  }, [])


  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="true" />
        <link href="https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;1,500&display=swap" rel="stylesheet" />
      </Head>

    </>
  )
}
